In [41]:
import sys
sys.path.insert(0, '..')
from simulation.road_factory import create_road

In [42]:
road = create_road()

In [43]:
demand = 8000
length = 2
speed = 95

In [47]:
density = demand / speed
density
d = density / 4
d

84.21052631578948

21.05263157894737

In [34]:
lane = road.network.get_lane(('west', 'east', 2))
lane

('west', 'east', 2) (U)
start=[0, 20] end=[500, 20]

In [76]:
np.random.uniform(0, 500, 20)

array([353.18684975, 252.52490469, 336.40068357, 248.52184095,
        52.53505405, 195.65559352, 148.07394256, 186.55888703,
       310.85151955,  87.07419008, 128.7217156 , 282.04078338,
       246.82423051, 461.03525692, 226.57979748,  51.14100384,
       179.21790951, 429.66764682,  83.08398955, 259.94277985])

In [75]:
adds = np.random.normal(d, 10, int(d))
adds

array([11.40566952, 21.33562133, 24.59338666, -2.63824674, 11.82732147,
       28.94786645, 26.06948136, 12.0998358 , 11.67370502, 11.51397865,
       17.51732514, 18.46631158, 16.28237555, 14.79719253, 30.55751805,
       22.94861365, 22.80407069, 10.22983396, 24.97872564, 28.04158914,
       12.17782257])

In [74]:
np.cumsum(adds)

array([ 24.00376296,  45.48247005,  60.33295458,  81.14039217,
        96.07175452, 116.99376854, 129.92276618, 152.13983824,
       174.70480059, 189.47563956, 208.25220001, 229.52720567,
       249.60624025, 269.7453176 , 290.49017674, 310.12651185,
       327.48845649, 350.62636378, 370.42659073, 395.14300655,
       415.09285353])